source "https://rubygems.org"

gem "sinatra"
gem "haml"
gem "sqlite3"
gem "activerecord"
gem "sinatra-activerecord", :require => "sinatra/activerecord"
gem "sass"
gem "compass"
gem "htmlentities"
gem "rake"